-- 테스트 소스에만 존재하는 BaseTimeEntity 검증용 엔티티.
CREATE TABLE IF NOT EXISTS base_time_test_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
