spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: "${DB_URL:jdbc:h2:file:./data/cbam;DB_CLOSE_ON_EXIT=FALSE}"
    username: "${DB_USERNAME:sa}"
    password: "${DB_PASSWORD:}"
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false
