CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE country (
    code varchar(2) PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    is_eu_member boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_registration_number varchar(40) NOT NULL,
    name varchar(120) NOT NULL,
    country_code varchar(2) NOT NULL,
    contact_name varchar(60) NOT NULL,
    contact_email varchar(254) NOT NULL,
    contact_phone varchar(30),
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    status_reason varchar(500),
    inactive_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_supplier_business_registration_number UNIQUE (business_registration_number),
    CONSTRAINT uk_supplier_contact_email UNIQUE (contact_email),
    CONSTRAINT fk_supplier_country FOREIGN KEY (country_code) REFERENCES country(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_supplier_inactive CHECK (status <> 'INACTIVE' OR (status_reason IS NOT NULL AND inactive_at IS NOT NULL))
);
CREATE UNIQUE INDEX uk_supplier_contact_email_lower ON supplier (lower(contact_email));
CREATE INDEX ix_supplier_name ON supplier (name);
CREATE INDEX ix_supplier_country_status ON supplier (country_code, status);

CREATE TABLE part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code varchar(40) NOT NULL UNIQUE,
    name varchar(120) NOT NULL UNIQUE,
    cn_code varchar(8) NOT NULL,
    unit varchar(10) NOT NULL,
    benchmark_factor numeric(10,4),
    benchmark_factor_year smallint,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_part_cn_code CHECK (cn_code ~ '^[0-9]{8}$'),
    CONSTRAINT ck_part_unit CHECK (unit IN ('KG', 'TON', 'EA')),
    CONSTRAINT ck_part_benchmark CHECK (benchmark_factor IS NULL OR benchmark_factor >= 0),
    CONSTRAINT ck_part_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX ix_part_cn_code ON part (cn_code);
CREATE INDEX ix_part_status ON part (status);

CREATE TABLE part_supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id bigint NOT NULL REFERENCES part(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    supplier_id bigint NOT NULL REFERENCES supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_part_supplier UNIQUE (part_id, supplier_id),
    CONSTRAINT ck_part_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX ix_part_supplier_supplier_status ON part_supplier (supplier_id, status);

CREATE TABLE product (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(120) NOT NULL,
    cn_code varchar(8) NOT NULL,
    annual_export_ton numeric(12,2) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_cn_code CHECK (cn_code ~ '^[0-9]{8}$'),
    CONSTRAINT ck_product_export CHECK (annual_export_ton >= 0),
    CONSTRAINT ck_product_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
CREATE INDEX ix_product_cn_code ON product (cn_code);
CREATE INDEX ix_product_status ON product (status);

CREATE TABLE product_export_country (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES product(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    country_code varchar(2) NOT NULL REFERENCES country(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_export_country UNIQUE (product_id, country_code)
);

CREATE TABLE product_part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL REFERENCES product(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    part_supplier_id bigint NOT NULL REFERENCES part_supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    input_qty_per_ton numeric(10,3) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_part UNIQUE (product_id, part_supplier_id),
    CONSTRAINT ck_product_part_quantity CHECK (input_qty_per_ton > 0)
);

CREATE TABLE mail_receipt (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint REFERENCES supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    reply_to_task_id varchar(50),
    message_id varchar(255) NOT NULL,
    sender_email varchar(254) NOT NULL,
    subject varchar(500),
    body text,
    in_reply_to_header varchar(1000),
    references_header text,
    status varchar(20) NOT NULL DEFAULT 'WAITING',
    failure_reason varchar(50),
    linked_by varchar(100),
    linked_at timestamptz,
    latest_analysis_task_id varchar(50),
    received_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_mail_receipt_message_id UNIQUE (message_id),
    CONSTRAINT ck_mail_receipt_status CHECK (status IN ('WAITING', 'MATCHED', 'UNMATCHED', 'REJECTED', 'ANALYZED', 'ANALYSIS_FAILED'))
);
CREATE INDEX ix_mail_receipt_supplier_received ON mail_receipt (supplier_id, received_at);
CREATE INDEX ix_mail_receipt_status_received ON mail_receipt (status, received_at);
CREATE INDEX ix_mail_receipt_sender_received ON mail_receipt (sender_email, received_at);
CREATE INDEX ix_mail_receipt_reply_task ON mail_receipt (reply_to_task_id);

CREATE TABLE attachment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_receipt_id bigint NOT NULL REFERENCES mail_receipt(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    original_filename varchar(500) NOT NULL,
    storage_uri varchar(1000) NOT NULL,
    mime_type varchar(150) NOT NULL,
    size_bytes bigint NOT NULL,
    -- 기존 Attachment 엔티티가 아직 체크섬을 쓰지 않으므로 CBAM-43에서는 nullable로 호환한다.
    checksum_sha256 varchar(64),
    process_status varchar(20) NOT NULL DEFAULT 'PENDING',
    extracted_text_uri varchar(1000),
    failure_reason varchar(50),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_attachment_receipt_checksum UNIQUE (mail_receipt_id, checksum_sha256),
    CONSTRAINT ck_attachment_size CHECK (size_bytes >= 0),
    CONSTRAINT ck_attachment_status CHECK (process_status IN ('PENDING', 'EXTRACTED', 'UNSUPPORTED', 'FAILED'))
);
CREATE INDEX ix_attachment_mail_receipt ON attachment (mail_receipt_id);
CREATE INDEX ix_attachment_process_status ON attachment (process_status);

CREATE TABLE submission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_receipt_id bigint NOT NULL REFERENCES mail_receipt(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    supplier_id bigint NOT NULL REFERENCES supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    part_supplier_id bigint REFERENCES part_supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    reporting_month date NOT NULL,
    document_type varchar(50),
    document_month date,
    production_quantity_ton numeric(14,3),
    production_country_code varchar(2) REFERENCES country(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    direct_emission_tco2e numeric(14,3),
    indirect_emission_tco2e numeric(14,3),
    default_value_ratio numeric(5,4),
    applied_factor_year smallint,
    applied_benchmark_factor numeric(10,4),
    factor_frozen_at timestamptz,
    status varchar(20) NOT NULL DEFAULT 'REVIEW_PENDING',
    judgement varchar(20),
    eligibility_status varchar(20),
    severity varchar(10),
    submitted_at timestamptz NOT NULL,
    confirmed_by varchar(100),
    confirmed_at timestamptz,
    rejected_by varchar(100),
    rejected_at timestamptz,
    rejection_reason_code varchar(50),
    rejection_reason text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_submission_month CHECK (date_trunc('month', reporting_month)::date = reporting_month AND (document_month IS NULL OR date_trunc('month', document_month)::date = document_month)),
    CONSTRAINT ck_submission_quantities CHECK ((production_quantity_ton IS NULL OR production_quantity_ton >= 0) AND (direct_emission_tco2e IS NULL OR direct_emission_tco2e >= 0) AND (indirect_emission_tco2e IS NULL OR indirect_emission_tco2e >= 0)),
    CONSTRAINT ck_submission_default_ratio CHECK (default_value_ratio IS NULL OR default_value_ratio BETWEEN 0 AND 1),
    CONSTRAINT ck_submission_status CHECK (status IN ('REVIEW_PENDING', 'CONFIRMED', 'REJECTED', 'NOT_SUBMITTED')),
    CONSTRAINT ck_submission_judgement CHECK (judgement IS NULL OR judgement IN ('QUALIFIED', 'UNQUALIFIED')),
    CONSTRAINT ck_submission_eligibility CHECK (eligibility_status IS NULL OR eligibility_status IN ('USABLE', 'NOT_USABLE')),
    CONSTRAINT ck_submission_severity CHECK (severity IS NULL OR severity IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_submission_confirmed CHECK (status <> 'CONFIRMED' OR (judgement = 'QUALIFIED' AND part_supplier_id IS NOT NULL AND confirmed_by IS NOT NULL AND confirmed_at IS NOT NULL AND factor_frozen_at IS NOT NULL)),
    CONSTRAINT ck_submission_rejected CHECK (status NOT IN ('REJECTED', 'NOT_SUBMITTED') OR (judgement = 'UNQUALIFIED' AND rejected_by IS NOT NULL AND rejected_at IS NOT NULL AND rejection_reason_code IS NOT NULL))
);
CREATE UNIQUE INDEX uk_submission_receipt_part_month ON submission (mail_receipt_id, part_supplier_id, reporting_month) WHERE part_supplier_id IS NOT NULL;
CREATE INDEX ix_submission_supplier_month_status ON submission (supplier_id, reporting_month, status);
CREATE INDEX ix_submission_part_month_status ON submission (part_supplier_id, reporting_month, status);
CREATE INDEX ix_submission_mail_receipt ON submission (mail_receipt_id);
CREATE INDEX ix_submission_judgement_severity ON submission (judgement, severity, submitted_at);

CREATE TABLE extraction_field (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES submission(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    source_attachment_id bigint REFERENCES attachment(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    field_code varchar(100) NOT NULL,
    sequence_number smallint NOT NULL DEFAULT 1,
    value_type varchar(20) NOT NULL,
    normalized_text text,
    normalized_decimal numeric(24,8),
    normalized_date date,
    normalized_country_code varchar(2) REFERENCES country(code) ON DELETE RESTRICT ON UPDATE CASCADE,
    unit varchar(30),
    raw_value text,
    emission_scope varchar(10),
    source_locator varchar(1000),
    conversion_failure_reason varchar(100),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_extraction_field_sequence UNIQUE (submission_id, field_code, sequence_number),
    CONSTRAINT ck_extraction_value_type CHECK (value_type IN ('TEXT', 'DECIMAL', 'DATE', 'COUNTRY_CODE')),
    CONSTRAINT ck_extraction_scope CHECK (emission_scope IS NULL OR emission_scope IN ('DIRECT', 'INDIRECT')),
    CONSTRAINT ck_extraction_failure_empty CHECK (conversion_failure_reason IS NULL OR (normalized_text IS NULL AND normalized_decimal IS NULL AND normalized_date IS NULL AND normalized_country_code IS NULL)),
    CONSTRAINT ck_extraction_normalized_type CHECK (
        conversion_failure_reason IS NOT NULL OR
        (value_type = 'TEXT' AND normalized_text IS NOT NULL AND normalized_decimal IS NULL AND normalized_date IS NULL AND normalized_country_code IS NULL) OR
        (value_type = 'DECIMAL' AND normalized_text IS NULL AND normalized_decimal IS NOT NULL AND normalized_date IS NULL AND normalized_country_code IS NULL) OR
        (value_type = 'DATE' AND normalized_text IS NULL AND normalized_decimal IS NULL AND normalized_date IS NOT NULL AND normalized_country_code IS NULL) OR
        (value_type = 'COUNTRY_CODE' AND normalized_text IS NULL AND normalized_decimal IS NULL AND normalized_date IS NULL AND normalized_country_code IS NOT NULL)
    )
);
CREATE INDEX ix_extraction_source_attachment ON extraction_field (source_attachment_id);
CREATE INDEX ix_extraction_scope ON extraction_field (emission_scope);

CREATE TABLE unregistered_part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES submission(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    raw_part_name varchar(500) NOT NULL,
    mapped_part_supplier_id bigint REFERENCES part_supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    status varchar(20) NOT NULL DEFAULT 'OPEN',
    resolved_by varchar(100),
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_unregistered_status CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT ck_unregistered_resolved CHECK (status <> 'RESOLVED' OR (mapped_part_supplier_id IS NOT NULL AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL))
);
CREATE INDEX ix_unregistered_submission_status ON unregistered_part (submission_id, status);
CREATE INDEX ix_unregistered_mapped_part ON unregistered_part (mapped_part_supplier_id);

CREATE TABLE task (
    id varchar(50) PRIMARY KEY,
    parent_task_id varchar(50) REFERENCES task(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    mail_receipt_id bigint REFERENCES mail_receipt(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    submission_id bigint REFERENCES submission(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    feedback_id bigint,
    feedback_draft_id bigint,
    type varchar(40) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    resource_type varchar(50),
    resource_ids jsonb,
    progress_total integer NOT NULL DEFAULT 0,
    progress_done integer NOT NULL DEFAULT 0,
    progress_failed integer NOT NULL DEFAULT 0,
    fallback_applied boolean NOT NULL DEFAULT false,
    unregistered_part_count integer NOT NULL DEFAULT 0,
    attempt_number smallint,
    resend_reason varchar(20),
    recipient_email varchar(254),
    external_message_id varchar(255) UNIQUE,
    error_code varchar(50),
    error_message text,
    requested_by varchar(100),
    sent_at timestamptz,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_task_type CHECK (type IN ('ANALYZE_MAIL_RECEIPT', 'REVALIDATE_SUBMISSION', 'SEND_REMINDER', 'GENERATE_FEEDBACK_DRAFT', 'REGENERATE_FEEDBACK_DRAFT', 'SEND_FEEDBACK')),
    CONSTRAINT ck_task_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_task_resend_reason CHECK (resend_reason IS NULL OR resend_reason IN ('SEND_FAILED', 'NO_REPLY')),
    CONSTRAINT ck_task_progress CHECK (progress_total >= 0 AND progress_done >= 0 AND progress_failed >= 0 AND progress_done + progress_failed <= progress_total),
    CONSTRAINT ck_task_completion CHECK ((status = 'COMPLETED' AND completed_at IS NOT NULL) OR (status = 'FAILED' AND error_code IS NOT NULL AND error_message IS NOT NULL AND completed_at IS NOT NULL) OR status IN ('PENDING', 'PROCESSING')),
    CONSTRAINT ck_task_send_fields CHECK (type NOT IN ('SEND_REMINDER', 'SEND_FEEDBACK') OR (feedback_id IS NOT NULL AND feedback_draft_id IS NOT NULL AND attempt_number IS NOT NULL AND recipient_email IS NOT NULL)),
    CONSTRAINT ck_task_attempt CHECK (attempt_number IS NULL OR (attempt_number = 1 AND resend_reason IS NULL) OR (attempt_number >= 2 AND resend_reason IS NOT NULL)),
    CONSTRAINT ck_task_sent CHECK (type NOT IN ('SEND_REMINDER', 'SEND_FEEDBACK') OR status <> 'COMPLETED' OR (external_message_id IS NOT NULL AND sent_at IS NOT NULL))
);
CREATE INDEX ix_task_status_created ON task (status, created_at);
CREATE INDEX ix_task_mail_type_created ON task (mail_receipt_id, type, created_at);
CREATE INDEX ix_task_submission_type_created ON task (submission_id, type, created_at);
CREATE INDEX ix_task_feedback_type_created ON task (feedback_id, type, created_at);
CREATE UNIQUE INDEX uk_task_feedback_attempt ON task (feedback_id, attempt_number) WHERE feedback_id IS NOT NULL AND attempt_number IS NOT NULL;

CREATE TABLE alert (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_supplier_id bigint REFERENCES part_supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    unregistered_part_id bigint REFERENCES unregistered_part(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    submission_id bigint REFERENCES submission(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    reporting_month date NOT NULL,
    rule_id varchar(10) NOT NULL,
    check_id varchar(50) NOT NULL,
    outcome varchar(10) NOT NULL,
    severity varchar(10) NOT NULL,
    observed_value varchar(255),
    reference_value varchar(255),
    message text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'OPEN',
    validated_at timestamptz NOT NULL,
    resolved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_alert_month CHECK (date_trunc('month', reporting_month)::date = reporting_month),
    CONSTRAINT ck_alert_rule CHECK (rule_id IN ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7')),
    CONSTRAINT ck_alert_outcome CHECK (outcome IN ('PASS', 'FAIL', 'SKIPPED')),
    CONSTRAINT ck_alert_severity CHECK (severity IN ('HIGH', 'MEDIUM', 'LOW')),
    CONSTRAINT ck_alert_status CHECK (status IN ('OPEN', 'RESOLVED', 'DISMISSED')),
    CONSTRAINT ck_alert_target CHECK ((rule_id = 'R1' AND submission_id IS NULL AND part_supplier_id IS NOT NULL) OR (rule_id <> 'R1' AND submission_id IS NOT NULL))
);
CREATE INDEX ix_alert_part_month_rule ON alert (part_supplier_id, reporting_month, rule_id, check_id);
CREATE INDEX ix_alert_unregistered_rule ON alert (unregistered_part_id, rule_id, check_id);
CREATE INDEX ix_alert_submission_rule ON alert (submission_id, rule_id, check_id);
CREATE INDEX ix_alert_status_severity_month ON alert (status, severity, reporting_month);

CREATE TABLE feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id bigint NOT NULL REFERENCES supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    part_supplier_id bigint REFERENCES part_supplier(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    submission_id bigint REFERENCES submission(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    confirmed_draft_id bigint,
    reporting_month date NOT NULL,
    type varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    recipient_email varchar(254),
    confirmed_by varchar(100),
    locked_at timestamptz,
    discarded_by varchar(100),
    discarded_at timestamptz,
    discard_reason text,
    created_by varchar(100),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_feedback_month CHECK (date_trunc('month', reporting_month)::date = reporting_month),
    CONSTRAINT ck_feedback_type CHECK (type IN ('FEEDBACK', 'REMINDER')),
    CONSTRAINT ck_feedback_status CHECK (status IN ('DRAFT', 'READY_TO_SEND', 'SENT', 'DISCARDED')),
    CONSTRAINT ck_feedback_target CHECK ((type = 'FEEDBACK' AND submission_id IS NOT NULL) OR (type = 'REMINDER' AND submission_id IS NULL)),
    CONSTRAINT ck_feedback_ready CHECK (status <> 'READY_TO_SEND' OR (confirmed_draft_id IS NOT NULL AND recipient_email IS NOT NULL AND confirmed_by IS NOT NULL AND locked_at IS NOT NULL)),
    CONSTRAINT ck_feedback_discarded CHECK (status <> 'DISCARDED' OR (discarded_by IS NOT NULL AND discarded_at IS NOT NULL AND discard_reason IS NOT NULL))
);
CREATE INDEX ix_feedback_supplier_month_type ON feedback (supplier_id, reporting_month, type);
CREATE INDEX ix_feedback_part_month ON feedback (part_supplier_id, reporting_month);
CREATE INDEX ix_feedback_submission ON feedback (submission_id);
CREATE INDEX ix_feedback_status_created ON feedback (status, created_at);

CREATE TABLE feedback_draft (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id bigint NOT NULL REFERENCES feedback(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    version_number smallint NOT NULL,
    source_type varchar(30) NOT NULL,
    style varchar(20) NOT NULL,
    instruction text,
    subject varchar(500) NOT NULL,
    body text NOT NULL,
    fallback_applied boolean NOT NULL DEFAULT false,
    fallback_template_id varchar(100),
    edited_by varchar(100),
    edited_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feedback_draft_version UNIQUE (feedback_id, version_number),
    CONSTRAINT ck_feedback_draft_version CHECK (version_number > 0),
    CONSTRAINT ck_feedback_draft_source CHECK (source_type IN ('AI', 'FALLBACK_TEMPLATE', 'HUMAN_EDIT')),
    CONSTRAINT ck_feedback_draft_style CHECK (style IN ('FORMAL', 'CONCISE', 'FRIENDLY')),
    CONSTRAINT ck_feedback_draft_fallback CHECK (source_type <> 'FALLBACK_TEMPLATE' OR (fallback_applied AND fallback_template_id IS NOT NULL))
);

ALTER TABLE feedback ADD CONSTRAINT fk_feedback_confirmed_draft FOREIGN KEY (confirmed_draft_id) REFERENCES feedback_draft(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE task ADD CONSTRAINT fk_task_feedback FOREIGN KEY (feedback_id) REFERENCES feedback(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE task ADD CONSTRAINT fk_task_feedback_draft FOREIGN KEY (feedback_draft_id) REFERENCES feedback_draft(id) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE mail_receipt ADD CONSTRAINT fk_mail_reply_task FOREIGN KEY (reply_to_task_id) REFERENCES task(id) ON DELETE RESTRICT ON UPDATE CASCADE;

DO $$
DECLARE table_name text;
BEGIN
    FOREACH table_name IN ARRAY ARRAY['country', 'supplier', 'part', 'part_supplier', 'product', 'product_export_country', 'product_part', 'mail_receipt', 'attachment', 'submission', 'extraction_field', 'unregistered_part', 'task', 'alert', 'feedback', 'feedback_draft']
    LOOP
        EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', table_name, table_name);
    END LOOP;
END $$;

-- 앱 전 환경에서 공통으로 사용하는 국가 기준정보.
INSERT INTO country (code, name, is_eu_member) VALUES
    ('AT', 'Austria', true),
    ('BE', 'Belgium', true),
    ('BG', 'Bulgaria', true),
    ('HR', 'Croatia', true),
    ('CY', 'Cyprus', true),
    ('CZ', 'Czechia', true),
    ('DK', 'Denmark', true),
    ('EE', 'Estonia', true),
    ('FI', 'Finland', true),
    ('FR', 'France', true),
    ('DE', 'Germany', true),
    ('GR', 'Greece', true),
    ('HU', 'Hungary', true),
    ('IE', 'Ireland', true),
    ('IT', 'Italy', true),
    ('LV', 'Latvia', true),
    ('LT', 'Lithuania', true),
    ('LU', 'Luxembourg', true),
    ('MT', 'Malta', true),
    ('NL', 'Netherlands', true),
    ('PL', 'Poland', true),
    ('PT', 'Portugal', true),
    ('RO', 'Romania', true),
    ('SK', 'Slovakia', true),
    ('SI', 'Slovenia', true),
    ('ES', 'Spain', true),
    ('SE', 'Sweden', true),
    ('CN', 'China', false),
    ('IN', 'India', false),
    ('ID', 'Indonesia', false),
    ('JP', 'Japan', false),
    ('KR', 'South Korea', false),
    ('TH', 'Thailand', false),
    ('US', 'United States', false),
    ('VN', 'Vietnam', false)
ON CONFLICT (code) DO NOTHING;
