-- ERD_v10.gj.md를 H2 문법으로 옮긴 팀 공용 스키마.
-- PostgreSQL 전용 JSONB는 H2 JSON으로 바꾸었다.
-- task.delivery_status는 현재 JPA 엔티티가 사용하는 확장 컬럼이다.

CREATE TABLE IF NOT EXISTS country (
    code CHAR(2) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_eu_member BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_registration_number VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL,
    country_code CHAR(2) NOT NULL,
    contact_name VARCHAR(60) NOT NULL,
    contact_email VARCHAR(254) NOT NULL UNIQUE,
    contact_phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    status_reason VARCHAR(500),
    inactive_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_supplier_country FOREIGN KEY (country_code) REFERENCES country(code),
    CONSTRAINT ck_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_supplier_inactive CHECK (
        status <> 'INACTIVE' OR (status_reason IS NOT NULL AND inactive_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code VARCHAR(40) NOT NULL UNIQUE,
    name VARCHAR(120) NOT NULL UNIQUE,
    cn_code CHAR(8) NOT NULL,
    unit VARCHAR(10) NOT NULL,
    benchmark_factor DECIMAL(10,4),
    benchmark_factor_year SMALLINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_part_cn_code CHECK (REGEXP_LIKE(cn_code, '^[0-9]{8}$')),
    CONSTRAINT ck_part_unit CHECK (unit IN ('KG', 'TON', 'EA')),
    CONSTRAINT ck_part_benchmark CHECK (benchmark_factor IS NULL OR benchmark_factor >= 0),
    CONSTRAINT ck_part_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS part_supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_part_supplier_part_supplier UNIQUE (part_id, supplier_id),
    CONSTRAINT fk_part_supplier_part FOREIGN KEY (part_id) REFERENCES part(id),
    CONSTRAINT fk_part_supplier_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    CONSTRAINT ck_part_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    cn_code CHAR(8) NOT NULL,
    annual_export_ton DECIMAL(12,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_product_cn_code CHECK (REGEXP_LIKE(cn_code, '^[0-9]{8}$')),
    CONSTRAINT ck_product_export CHECK (annual_export_ton >= 0),
    CONSTRAINT ck_product_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS product_export_country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    country_code CHAR(2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_export_country UNIQUE (product_id, country_code),
    CONSTRAINT fk_product_export_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_product_export_country FOREIGN KEY (country_code) REFERENCES country(code)
);

CREATE TABLE IF NOT EXISTS product_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    part_supplier_id BIGINT NOT NULL,
    input_qty_per_ton DECIMAL(10,3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_part_supplier UNIQUE (product_id, part_supplier_id),
    CONSTRAINT fk_product_part_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_product_part_supplier FOREIGN KEY (part_supplier_id) REFERENCES part_supplier(id),
    CONSTRAINT ck_product_part_qty CHECK (input_qty_per_ton > 0)
);

CREATE TABLE IF NOT EXISTS mail_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT,
    reply_to_task_id VARCHAR(50),
    message_id VARCHAR(255) NOT NULL UNIQUE,
    sender_email VARCHAR(254) NOT NULL,
    subject VARCHAR(500),
    body TEXT,
    in_reply_to_header VARCHAR(1000),
    references_header TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    failure_reason VARCHAR(50),
    linked_by VARCHAR(100),
    linked_at TIMESTAMP WITH TIME ZONE,
    -- 현재 메일 분석 API가 최신 비동기 작업을 추적하기 위해 사용하는 확장 컬럼.
    latest_analysis_task_id VARCHAR(50),
    received_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mail_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    CONSTRAINT ck_mail_status CHECK (status IN ('WAITING','MATCHED','UNMATCHED','REJECTED','ANALYZED','ANALYSIS_FAILED'))
);

CREATE TABLE IF NOT EXISTS attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_receipt_id BIGINT NOT NULL,
    original_filename VARCHAR(500) NOT NULL,
    storage_uri VARCHAR(1000) NOT NULL,
    mime_type VARCHAR(150) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    process_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    extracted_text_uri VARCHAR(1000),
    failure_reason VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_attachment_mail_checksum UNIQUE (mail_receipt_id, checksum_sha256),
    CONSTRAINT fk_attachment_mail FOREIGN KEY (mail_receipt_id) REFERENCES mail_receipt(id),
    CONSTRAINT ck_attachment_status CHECK (process_status IN ('PENDING','EXTRACTED','UNSUPPORTED','FAILED'))
);

CREATE TABLE IF NOT EXISTS submission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mail_receipt_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    part_supplier_id BIGINT,
    reporting_month DATE NOT NULL,
    document_type VARCHAR(50),
    document_month DATE,
    production_quantity_ton DECIMAL(14,3),
    production_country_code CHAR(2),
    direct_emission_tco2e DECIMAL(14,3),
    indirect_emission_tco2e DECIMAL(14,3),
    default_value_ratio DECIMAL(5,4),
    applied_factor_year SMALLINT,
    applied_benchmark_factor DECIMAL(10,4),
    factor_frozen_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(20) NOT NULL DEFAULT 'REVIEW_PENDING',
    judgement VARCHAR(20),
    eligibility_status VARCHAR(20),
    severity VARCHAR(10),
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmed_by VARCHAR(100),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    rejected_by VARCHAR(100),
    rejected_at TIMESTAMP WITH TIME ZONE,
    rejection_reason_code VARCHAR(50),
    rejection_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_submission_mail FOREIGN KEY (mail_receipt_id) REFERENCES mail_receipt(id),
    CONSTRAINT fk_submission_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    CONSTRAINT fk_submission_part_supplier FOREIGN KEY (part_supplier_id) REFERENCES part_supplier(id),
    CONSTRAINT fk_submission_country FOREIGN KEY (production_country_code) REFERENCES country(code),
    CONSTRAINT ck_submission_month CHECK (DAY(reporting_month) = 1 AND (document_month IS NULL OR DAY(document_month) = 1)),
    CONSTRAINT ck_submission_values CHECK (
        (production_quantity_ton IS NULL OR production_quantity_ton >= 0)
        AND (direct_emission_tco2e IS NULL OR direct_emission_tco2e >= 0)
        AND (indirect_emission_tco2e IS NULL OR indirect_emission_tco2e >= 0)
        AND (default_value_ratio IS NULL OR default_value_ratio BETWEEN 0 AND 1)
    )
);

CREATE TABLE IF NOT EXISTS extraction_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    source_attachment_id BIGINT,
    field_code VARCHAR(100) NOT NULL,
    sequence_number SMALLINT NOT NULL DEFAULT 1,
    value_type VARCHAR(20) NOT NULL,
    normalized_text TEXT,
    normalized_decimal DECIMAL(24,8),
    normalized_date DATE,
    normalized_country_code CHAR(2),
    unit VARCHAR(30),
    raw_value TEXT,
    emission_scope VARCHAR(10),
    source_locator VARCHAR(1000),
    conversion_failure_reason VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_extraction_field UNIQUE (submission_id, field_code, sequence_number),
    CONSTRAINT fk_extraction_submission FOREIGN KEY (submission_id) REFERENCES submission(id),
    CONSTRAINT fk_extraction_attachment FOREIGN KEY (source_attachment_id) REFERENCES attachment(id),
    CONSTRAINT fk_extraction_country FOREIGN KEY (normalized_country_code) REFERENCES country(code)
);

CREATE TABLE IF NOT EXISTS unregistered_part (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL,
    raw_part_name VARCHAR(500) NOT NULL,
    mapped_part_supplier_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_unregistered_submission FOREIGN KEY (submission_id) REFERENCES submission(id),
    CONSTRAINT fk_unregistered_mapping FOREIGN KEY (mapped_part_supplier_id) REFERENCES part_supplier(id),
    CONSTRAINT ck_unregistered_resolved CHECK (
        status <> 'RESOLVED' OR (mapped_part_supplier_id IS NOT NULL AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    part_supplier_id BIGINT,
    submission_id BIGINT,
    confirmed_draft_id BIGINT,
    reporting_month DATE NOT NULL,
    type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    recipient_email VARCHAR(254),
    confirmed_by VARCHAR(100),
    locked_at TIMESTAMP WITH TIME ZONE,
    discarded_by VARCHAR(100),
    discarded_at TIMESTAMP WITH TIME ZONE,
    discard_reason TEXT,
    created_by VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feedback_supplier FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    CONSTRAINT fk_feedback_part_supplier FOREIGN KEY (part_supplier_id) REFERENCES part_supplier(id),
    CONSTRAINT fk_feedback_submission FOREIGN KEY (submission_id) REFERENCES submission(id)
);

CREATE TABLE IF NOT EXISTS feedback_draft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feedback_id BIGINT NOT NULL,
    version_number SMALLINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    style VARCHAR(20) NOT NULL,
    instruction TEXT,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    fallback_applied BOOLEAN NOT NULL DEFAULT FALSE,
    fallback_template_id VARCHAR(100),
    edited_by VARCHAR(100),
    edited_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_feedback_draft_feedback_version UNIQUE (feedback_id, version_number),
    CONSTRAINT fk_draft_feedback FOREIGN KEY (feedback_id) REFERENCES feedback(id)
);

CREATE TABLE IF NOT EXISTS task (
    id VARCHAR(50) PRIMARY KEY,
    parent_task_id VARCHAR(50),
    mail_receipt_id BIGINT,
    submission_id BIGINT,
    feedback_id BIGINT,
    feedback_draft_id BIGINT,
    type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    delivery_status VARCHAR(20),
    resource_type VARCHAR(50),
    resource_ids JSON,
    progress_total INTEGER NOT NULL DEFAULT 0,
    progress_done INTEGER NOT NULL DEFAULT 0,
    progress_failed INTEGER NOT NULL DEFAULT 0,
    fallback_applied BOOLEAN NOT NULL DEFAULT FALSE,
    unregistered_part_count INTEGER NOT NULL DEFAULT 0,
    attempt_number SMALLINT,
    resend_reason VARCHAR(20),
    recipient_email VARCHAR(254),
    external_message_id VARCHAR(255) UNIQUE,
    error_code VARCHAR(50),
    error_message TEXT,
    requested_by VARCHAR(100),
    sent_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_task_parent FOREIGN KEY (parent_task_id) REFERENCES task(id),
    CONSTRAINT fk_task_mail FOREIGN KEY (mail_receipt_id) REFERENCES mail_receipt(id),
    CONSTRAINT fk_task_submission FOREIGN KEY (submission_id) REFERENCES submission(id),
    CONSTRAINT fk_task_feedback FOREIGN KEY (feedback_id) REFERENCES feedback(id),
    CONSTRAINT fk_task_draft FOREIGN KEY (feedback_draft_id) REFERENCES feedback_draft(id),
    CONSTRAINT ck_task_progress CHECK (progress_done + progress_failed <= progress_total)
);

CREATE TABLE IF NOT EXISTS alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_supplier_id BIGINT,
    unregistered_part_id BIGINT,
    submission_id BIGINT,
    reporting_month DATE NOT NULL,
    rule_id VARCHAR(10) NOT NULL,
    check_id VARCHAR(50) NOT NULL,
    outcome VARCHAR(10) NOT NULL,
    severity VARCHAR(10) NOT NULL,
    observed_value VARCHAR(255),
    reference_value VARCHAR(255),
    message TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    validated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_alert_part_supplier FOREIGN KEY (part_supplier_id) REFERENCES part_supplier(id),
    CONSTRAINT fk_alert_unregistered FOREIGN KEY (unregistered_part_id) REFERENCES unregistered_part(id),
    CONSTRAINT fk_alert_submission FOREIGN KEY (submission_id) REFERENCES submission(id),
    CONSTRAINT ck_alert_rule CHECK (rule_id IN ('R1','R2','R3','R4','R5','R6','R7'))
);

ALTER TABLE mail_receipt ADD CONSTRAINT IF NOT EXISTS fk_mail_reply_task
    FOREIGN KEY (reply_to_task_id) REFERENCES task(id);
ALTER TABLE feedback ADD CONSTRAINT IF NOT EXISTS fk_feedback_confirmed_draft
    FOREIGN KEY (confirmed_draft_id) REFERENCES feedback_draft(id);

CREATE INDEX IF NOT EXISTS ix_supplier_name ON supplier(name);
CREATE INDEX IF NOT EXISTS ix_supplier_country_status ON supplier(country_code, status);
CREATE INDEX IF NOT EXISTS ix_part_cn_code ON part(cn_code);
CREATE INDEX IF NOT EXISTS ix_part_status ON part(status);
CREATE INDEX IF NOT EXISTS ix_part_supplier_supplier_status ON part_supplier(supplier_id, status);
CREATE INDEX IF NOT EXISTS ix_product_cn_code ON product(cn_code);
CREATE INDEX IF NOT EXISTS ix_product_status ON product(status);
CREATE INDEX IF NOT EXISTS ix_mail_supplier_received ON mail_receipt(supplier_id, received_at);
CREATE INDEX IF NOT EXISTS ix_mail_status_received ON mail_receipt(status, received_at);
CREATE INDEX IF NOT EXISTS ix_mail_sender_received ON mail_receipt(sender_email, received_at);
CREATE INDEX IF NOT EXISTS ix_mail_reply_task ON mail_receipt(reply_to_task_id);
CREATE INDEX IF NOT EXISTS ix_attachment_status ON attachment(process_status);
CREATE INDEX IF NOT EXISTS ix_submission_supplier_month_status ON submission(supplier_id, reporting_month, status);
CREATE INDEX IF NOT EXISTS ix_submission_part_month_status ON submission(part_supplier_id, reporting_month, status);
CREATE INDEX IF NOT EXISTS ix_submission_mail ON submission(mail_receipt_id);
CREATE INDEX IF NOT EXISTS ix_submission_judgement_severity_submitted ON submission(judgement, severity, submitted_at);
CREATE INDEX IF NOT EXISTS ix_extraction_attachment ON extraction_field(source_attachment_id);
CREATE INDEX IF NOT EXISTS ix_extraction_scope ON extraction_field(emission_scope);
CREATE INDEX IF NOT EXISTS ix_unregistered_submission_status ON unregistered_part(submission_id, status);
CREATE INDEX IF NOT EXISTS ix_unregistered_mapping ON unregistered_part(mapped_part_supplier_id);
CREATE INDEX IF NOT EXISTS ix_alert_part_month_rule_check ON alert(part_supplier_id, reporting_month, rule_id, check_id);
CREATE INDEX IF NOT EXISTS ix_alert_unregistered_rule_check ON alert(unregistered_part_id, rule_id, check_id);
CREATE INDEX IF NOT EXISTS ix_alert_submission_rule_check ON alert(submission_id, rule_id, check_id);
CREATE INDEX IF NOT EXISTS ix_alert_status_severity_month ON alert(status, severity, reporting_month);
CREATE INDEX IF NOT EXISTS ix_feedback_supplier_month_type ON feedback(supplier_id, reporting_month, type);
CREATE INDEX IF NOT EXISTS ix_feedback_part_month ON feedback(part_supplier_id, reporting_month);
CREATE INDEX IF NOT EXISTS ix_feedback_submission ON feedback(submission_id);
CREATE INDEX IF NOT EXISTS ix_feedback_status_created ON feedback(status, created_at);
CREATE INDEX IF NOT EXISTS ix_feedback_draft_feedback ON feedback_draft(feedback_id);
CREATE INDEX IF NOT EXISTS ix_task_status_created ON task(status, created_at);
CREATE INDEX IF NOT EXISTS ix_task_mail_type_created ON task(mail_receipt_id, type, created_at);
CREATE INDEX IF NOT EXISTS ix_task_submission_type_created ON task(submission_id, type, created_at);
CREATE INDEX IF NOT EXISTS ix_task_feedback_type_created ON task(feedback_id, type, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uk_task_feedback_attempt ON task(feedback_id, attempt_number);
